# Generated by Django 5.0.1 on 2024-01-30 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='firstname',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='lastname',
            new_name='lastName',
        ),
    ]
