# Generated by Django 5.0.2 on 2024-03-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_journalentry_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='background_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
    ]
