# Generated by Django 5.0.2 on 2024-03-23 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_journalentry_background_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='user',
        ),
    ]
