# Generated by Django 4.2.1 on 2024-06-28 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
