# Generated by Django 4.2.1 on 2024-09-19 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0008_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('happiness', models.IntegerField()),
                ('anxiety', models.CharField(max_length=20)),
                ('energy', models.CharField(max_length=20)),
                ('sleep_quality', models.IntegerField()),
                ('appetite', models.IntegerField()),
                ('physical_health', models.IntegerField()),
                ('concentration', models.IntegerField()),
                ('social_connections', models.IntegerField()),
                ('stress_level', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
