# Generated by Django 5.2.8 on 2025-11-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_chatthread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatthread',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
